# Generated by Django 6.0 on 2025-12-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=150)),
                ('machine_name', models.CharField(max_length=150, unique=True)),
                ('machine_code', models.CharField(max_length=150, unique=True)),
                ('machine_model', models.CharField(max_length=150, unique=True)),
                ('machine_serial', models.CharField(max_length=150, unique=True)),
                ('manufacture_year', models.PositiveIntegerField(verbose_name='Manufacture Year')),
                ('company_entry_date', models.DateField(verbose_name='Company Entry Date')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='Installation Date')),
                ('criticality_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=50, verbose_name='Criticality Level')),
                ('location_name', models.CharField(max_length=255, verbose_name='Location Name')),
                ('location_code', models.CharField(max_length=100, verbose_name='Location Code')),
                ('length_mm', models.FloatField(blank=True, null=True, verbose_name='Length (mm)')),
                ('width_mm', models.FloatField(blank=True, null=True, verbose_name='Width (mm)')),
                ('height_mm', models.FloatField(blank=True, null=True, verbose_name='Height (mm)')),
                ('weight_kg', models.FloatField(blank=True, null=True, verbose_name='Weight (kg)')),
                ('foundation_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Foundation Type')),
                ('automation_level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Automation Level')),
                ('has_guarantee', models.BooleanField(default=False, verbose_name='Guarantee')),
                ('guarantee_expiry_date', models.DateField(blank=True, null=True, verbose_name='Guarantee Expiry Date')),
                ('has_warranty', models.BooleanField(default=False, verbose_name='Warranty')),
                ('warranty_expiry_date', models.DateField(blank=True, null=True, verbose_name='Warranty Expiry Date')),
                ('current_type', models.CharField(choices=[('AC', 'AC'), ('DC', 'DC')], max_length=10, verbose_name='Current Type')),
                ('phase_count', models.PositiveSmallIntegerField(verbose_name='Number of Phases')),
                ('nominal_voltage', models.FloatField(verbose_name='Nominal Voltage (V)')),
                ('nominal_power', models.FloatField(verbose_name='Nominal Power (kW)')),
                ('nominal_current', models.FloatField(verbose_name='Nominal Current (A)')),
                ('electrical_technical_description', models.TextField(blank=True, null=True, verbose_name='Electrical Technical Description')),
                ('maximum_consumption', models.FloatField(blank=True, null=True, verbose_name='Maximum Consumption')),
                ('operating_pressure', models.FloatField(blank=True, null=True, verbose_name='Pressure')),
                ('lubricant_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lubricant Type')),
                ('alternative_lubricant_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternative Lubricant Type')),
                ('lubricant_description', models.TextField(blank=True, null=True, verbose_name='Lubricant Description')),
                ('supplier_company_name', models.CharField(max_length=255, verbose_name='Supplier Company Name')),
                ('supplier_phone', models.CharField(max_length=50, verbose_name='Supplier Phone')),
                ('supplier_address', models.TextField(verbose_name='Supplier Address')),
                ('manufacturer_company_name', models.CharField(max_length=255, verbose_name='Manufacturer Company Name')),
                ('manufacturer_phone', models.CharField(max_length=50, verbose_name='Manufacturer Phone')),
                ('manufacturer_address', models.TextField(verbose_name='Manufacturer Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
