# Generated by Django 6.0 on 2025-12-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
