# Generated by Django 5.2.8 on 2025-12-30 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinlist', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineregistration',
            name='alternative_lubricant_type',
        ),
        migrations.RemoveField(
            model_name='machineregistration',
            name='lubricant_description',
        ),
        migrations.RemoveField(
            model_name='machineregistration',
            name='lubricant_type',
        ),
        migrations.AlterField(
            model_name='machineregistration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='MachineLubricant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveSmallIntegerField(default=1, verbose_name='Row Number')),
                ('lubricant_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lubricant Type')),
                ('alternative_lubricant_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alternative Lubricant Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lubricants', to='machinlist.machineregistration')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
    ]
