# Generated by Django 5.2.8 on 2025-12-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinlist', '0003_remove_machineregistration_alternative_lubricant_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
